version: '3'

services:

  nginx:
    build:
      context: ./nginx
    image: bborghif/nginx:prod
    container_name: nginx
    networks:
      - borghinet
    ports:
      - "8080:80"
    depends_on:
     - nodeserver

  nodeserver:
    build:
      context: node
    image: bborghif/node:prod
    container_name: nodeserver
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s bash -c "npm install && node index.js"
    networks:
      - borghinet
    volumes:
     - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    build:
      context: ./mysql
    image: bborghif/mysql:prod
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
     - borghinet

networks:
  borghinet:
    driver: bridge